run:
  # include test files or not, default is true
  tests: false
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - forbidigo
    - gci
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - makezero
    - misspell
    - nakedret
    - nestif
    - promlinter
    - revive
linters-settings:
  gocyclo:
    min-complexity: 15