version: "2"
run:
  # include test files or not, default is true
  tests: false
formatters:
  enable:
    - gci
    - gofmt
    - goimports
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - forbidigo
    - goconst
    - gocyclo
    - godot
    - makezero
    - misspell
    - nakedret
    - nestif
    - promlinter
    - revive
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
