{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k6-loadtester.serviceAccountName" . }}
  labels:
    {{- include "k6-loadtester.labels" . | nindent 4 }}
  annotations: {{ .Values.serviceAccount.annotations | toYaml}}
{{- end }}