---
environment:
  CGO_ENABLED: "0"
  GOARCH: amd64
  GOOS: linux
kind: pipeline
name: test
steps:
- commands:
  - go build ./...
  image: golang:1.17-alpine
  name: build
- commands:
  - go test ./...
  image: golang:1.17-alpine
  name: test
- commands:
  - golangci-lint run
  image: golangci/golangci-lint
  name: lint
trigger:
  event:
    include:
    - pull_request
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: docker
steps:
- commands:
  - git fetch --tags
  image: alpine/git
  name: fetch tags
- commands:
  - apk add git make
  - echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
  - make build
  environment:
    CR_PAT:
      from_secret: github_token
  image: docker
  name: build
  volumes:
  - name: docker
    path: /var/run/docker.sock
- commands:
  - apk add git make
  - echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
  - make push
  environment:
    CR_PAT:
      from_secret: github_token
  image: docker
  name: push tag
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag
- commands:
  - apk add git make
  - echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
  - make push-latest
  environment:
    CR_PAT:
      from_secret: github_token
  image: docker
  name: push latest
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - push
trigger:
  branch:
    include:
    - main
  event:
    include:
    - pull_request
    - push
    - tag
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: github_token
---
kind: signature
hmac: 14a3bd4b542025e1392b16e3c8b4b306eb689ff8fc2c02f371aee35757543edd

...
