---
environment:
  CGO_ENABLED: "0"
  GOARCH: amd64
  GOOS: linux
kind: pipeline
name: test
steps:
- commands:
  - go build ./...
  image: golang:1.17-alpine
  name: build
- commands:
  - go test ./...
  image: golang:1.17-alpine
  name: test
- commands:
  - golangci-lint run
  image: golangci/golangci-lint
  name: lint
trigger:
  event:
    include:
    - push
---
kind: pipeline
name: docker
steps:
- commands:
  - apk add make
  - echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
  - make build
  environment:
    CR_PAT:
      from_secret: github_token
  image: docker
  name: build
  volumes:
  - name: docker
    path: /var/run/docker.sock
- commands:
  - apk add make
  - echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
  - make push
  environment:
    CR_PAT:
      from_secret: github_token
  image: docker
  name: push tag
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag
- commands:
  - apk add make
  - echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
  - make push-latest
  environment:
    CR_PAT:
      from_secret: github_token
  image: docker
  name: push latest
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - main
    event:
    - push
trigger:
  event:
    include:
    - push
    - tag
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: github_token
---
kind: signature
hmac: 2d38a1c50537a55de5f47e826658a0ebe7a87c0ef5b80fbce94e84b12c659d35

...
