---
kind: pipeline
name: docker
steps:
- commands:
  - echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
  environment:
    CR_PAT:
      from_secret: github_token
  image: docker
  name: push latest
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  event:
    include:
    - pull_request
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: github_token
---
kind: signature
hmac: 5db87893409efedcb6170926f39151aee459ef85d9174d1ff430878f066ccfc4

...
