---
kind: pipeline
name: docker
steps:
- commands:
  - echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
  - echo $CR_PAT | wc -c
  environment:
    CR_PAT:
      from_secret: github_token
  image: docker
  name: push latest
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  event:
    include:
    - pull_request
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: github_token
---
kind: signature
hmac: 997fbd946d1f717cafe91e61ceafa197d66efc2c6f6b5fddc68dc29a88fd7833

...
