on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: "${{ steps.release-please.outputs.release_created }}"
      release_tag: "${{ steps.release-please.outputs.tag_name }}"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release-please
        with:
          config-file: .release-please.json
          manifest-file: .release-please-manifest.json

  release-docker-image:
    needs:
      - release-please
    if: needs.release-please.outputs.release_created
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker.yml
    with:
      tag: ${{ needs.release-please.outputs.release_tag }}
